import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/ui/Sidebar";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-center justify-between`}>
        <Sidebar />
        <main className="grid  w-full h-full pl-[300px]">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
